import Testing

@testable import AdventOfCode

struct Day07Tests {

  let testInput1 = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """

  @Test func testPart1() async throws {
    #expect(String(describing: Day07(data: testInput1).part1()) == "21")
  }

  @Test func testPart2() async throws {
    #expect(String(describing: Day07(data: testInput1).part2()) == "40")
  }
}
